### ISSUE TITLE
About password.

### ISSUE THREAD

**Issue by Spider4eyes** [MR-S74RK/FB-HACK#3]
How much usd for the zip password?

**Comment by MR-S74RK** [comment]
7.34$

**Comment by Spider4eyes** [comment]
It's not a big deal. But May you support me too? Is it just simple that run the command and get the password or we need to know something else?
I am using winsdow 10, by the way

**Comment by Spider4eyes** [comment]
@MR-S74RK

**Comment by LEO1234567890LEO** [comment]
Sure  its the turtorial

**Comment by LEO1234567890LEO** [comment]
https://drive.google.com/file/d/1aQczDE57w-R0tAKaltsUeEL16asNsIEO/view?usp=drivesdk

**Comment by MR-S74RK** [comment]
Yeah but no trail available

**Comment by Spider4eyes** [comment]
Do you have paypal? I will send and get the password

**Comment by MR-S74RK** [comment]
https://www.paypal.me/Starkserind 
First money then password

**Comment by Spider4eyes** [comment]
I cannot transfer, the paypal says you dont accept the payment

**Comment by Spider4eyes** [comment]
Can u unblock?

**Comment by Spider4eyes** [comment]
I think your paypal account is not verified

**Comment by MR-S74RK** [comment]
Can you send money through goftcard amazon.in giftcard?

**Comment by MR-S74RK** [comment]
https://dundle.com/in/amazon/500-inr-in/
Buy this one 
It just only 6.11$

**Comment by Spider4eyes** [comment]
I cannot buy as well. It always cancelled. I have an idea, give me your usdtd(trc-20), i will sent 7,34 usdt to your wallet

**Comment by MR-S74RK** [comment]
That's not available,, Bro try to buy Amazon giftcard in Amazon india

**Comment by Spider4eyes** [comment]
Ok. I bought it. I just need to send you the code by email right??

**Comment by Spider4eyes** [comment]
Hello! I bought it! Could you send me the password?

**Comment by MR-S74RK** [comment]
Email : gamerunknown509@gmail.com
Send it and i will give password

**Comment by Spider4eyes** [comment]
Done. Send me to email spider4eye@gmail.com

**Comment by Spider4eyes** [comment]
I cannot run it! Could you guild me?

**Comment by Spider4eyes** [comment]
![image](https://user-images.githubusercontent.com/130431285/236123527-869f8513-7b0a-4e40-9de1-26db18aff74c.png)
I got the error

**Comment by MR-S74RK** [comment]
Press 1 bro and came to email other instructions will provide there✅

**Comment by Spider4eyes** [comment]
is it possible with the id?
