### ISSUE TITLE
you tools is carck shit 

### ISSUE THREAD

**Issue by LAPSCA** [MR-S74RK/FB-HACK#4]
don't use this tool is fake

**Comment by MR-S74RK** [comment]
You dont used it sh** so don't mess up.. 
Challenge

**Comment by MR-S74RK** [comment]
First learn the spell of crack ?
Then tell want a trail or not shit
This the Turtorial weare going to allow a 1btime turtorial for the tool
https://drive.google.com/file/d/1aQczDE57w-R0tAKaltsUeEL16asNsIEO/view?usp=drivesdk
