### ISSUE TITLE
Password for zipfile

### ISSUE THREAD

**Issue by Mallorcan99** [MR-S74RK/FB-HACK#6]
![Screenshot_20230508-211604_Termux](https://user-images.githubusercontent.com/132750348/236900402-542d4bf7-ba59-4178-a113-c26462bafa69.jpg)

Any ideas?

**Comment by MR-S74RK** [comment]
Its paid 7.36$

**Comment by Bnja123ejje** [comment]
Password?

**Comment by LEO1234567890LEO** [comment]
@Bnja123ejje password is paid $7.33
