### ISSUE TITLE
ZIP PASSWORD

### ISSUE THREAD

**Issue by d4rks0ul555** [MR-S74RK/FB-HACK#7]
what is the zip password?

**Comment by gromsop** [comment]
zip password please ?

**Comment by MR-S74RK** [comment]
Zip pass is paid 7.33$

**Comment by gromsop** [comment]
> Zip pass is paid 7.33$

How can i pay ?
Your paypal account not work
Did you have another solution ?

**Comment by MR-S74RK** [comment]
Amazon.in giftcard. Or btc

**Comment by gromsop** [comment]
I have send you an email yesterday without any reply.
Where is the link of Amazon gift ?

**Comment by hvacmannn** [comment]
> what is the zip password?

cmon MAN git with the GAME,,.....

**Comment by LEO1234567890LEO** [comment]
contact me @ gamerunknown509@gmail.com
